name: demo

services:
  cardano-node:
    # https://github.com/cardano-scaling/hydra/blob/master/demo/docker-compose.yaml
    image: ghcr.io/intersectmbo/cardano-node:10.2
    volumes:
      - ./devnet:/devnet
    environment:
      - CARDANO_BLOCK_PRODUCER=true
      - CARDANO_SOCKET_PATH=/devnet/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/devnet/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/devnet/cardano-node.json"
      , "--topology", "/devnet/topology.json"
      , "--database-path", "/devnet/db"
      , "--shelley-kes-key", "/devnet/kes.skey"
      , "--shelley-vrf-key", "/devnet/vrf.skey"
      , "--shelley-operational-certificate", "/devnet/opcert.cert"
      , "--byron-delegation-certificate", "/devnet/byron-delegation.cert"
      , "--byron-signing-key", "/devnet/byron-delegate.key"
      ]
    healthcheck:
      test: [ "CMD-SHELL", "(</dev/tcp/localhost/3001) && echo OK && exit 0 || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - hydra_net
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  hydra-node-1:
    # NOTE: Make sure to use the same image in ./seed-devnet.sh
    image: ghcr.io/cardano-scaling/hydra-node:0.22.0
    build:
      context: ../
      target: hydra-node
    volumes:
      - ./keys:/keys:ro
      - ./devnet:/devnet
    ports:
      - "4001:4001"
      - "5001:5001"
    command:
      [ "--node-id", "1"
      , "--api-host", "0.0.0.0"
      , "--listen", "172.16.238.10:5001"
      , "--monitoring-port", "6001"
      , "--peer", "172.16.238.20:5001"
      , "--peer", "172.16.238.30:5001"
      , "--hydra-scripts-tx-id", "${HYDRA_SCRIPTS_TX_ID}"
      , "--hydra-signing-key", "/keys/alice.sk"
      , "--hydra-verification-key", "/keys/bob.vk"
      , "--hydra-verification-key", "/keys/carol.vk"
      , "--cardano-signing-key", "/devnet/credentials/alice.sk"
      , "--cardano-verification-key", "/devnet/credentials/bob.vk"
      , "--cardano-verification-key", "/devnet/credentials/carol.vk"
      , "--ledger-protocol-parameters", "/devnet/protocol-parameters.json"
      , "--testnet-magic", "42"
      , "--node-socket", "/devnet/node.socket"
      , "--persistence-dir", "/devnet/persistence/alice"
      , "--contestation-period", "3s"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.10
    restart: always

  hydra-node-2:
    # NOTE: Make sure to use the same image in ./seed-devnet.sh
    image: ghcr.io/cardano-scaling/hydra-node:0.22.0
    build:
      context: ../
      target: hydra-node
    volumes:
      - ./keys:/keys:ro
      - ./devnet:/devnet
    ports:
      - "4002:4001"
      - "5002:5001"
    command:
      [ "--node-id", "2"
      , "--api-host", "0.0.0.0"
      , "--listen", "172.16.238.20:5001"
      , "--monitoring-port", "6001"
      , "--peer", "172.16.238.10:5001"
      , "--peer", "172.16.238.30:5001"
      , "--hydra-scripts-tx-id", "${HYDRA_SCRIPTS_TX_ID}"
      , "--hydra-signing-key", "/keys/bob.sk"
      , "--hydra-verification-key", "/keys/alice.vk"
      , "--hydra-verification-key", "/keys/carol.vk"
      , "--cardano-signing-key", "/devnet/credentials/bob.sk"
      , "--cardano-verification-key", "/devnet/credentials/alice.vk"
      , "--cardano-verification-key", "/devnet/credentials/carol.vk"
      , "--ledger-protocol-parameters", "/devnet/protocol-parameters.json"
      , "--testnet-magic", "42"
      , "--node-socket", "/devnet/node.socket"
      , "--persistence-dir", "/devnet/persistence/bob"
      , "--contestation-period", "3s"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.20
    restart: always

  hydra-node-3:
    # NOTE: Make sure to use the same image in ./seed-devnet.sh
    image: ghcr.io/cardano-scaling/hydra-node:0.22.0
    build:
      context: ../
      target: hydra-node
    volumes:
      - ./keys:/keys:ro
      - ./devnet:/devnet
    ports:
      - "4003:4001"
      - "5003:5001"
    command:
      [ "--node-id", "3"
      , "--api-host", "0.0.0.0"
      , "--listen", "172.16.238.30:5001"
      , "--monitoring-port", "6001"
      , "--peer", "172.16.238.10:5001"
      , "--peer", "172.16.238.20:5001"
      , "--hydra-scripts-tx-id", "${HYDRA_SCRIPTS_TX_ID}"
      , "--hydra-signing-key", "/keys/carol.sk"
      , "--hydra-verification-key", "/keys/alice.vk"
      , "--hydra-verification-key", "/keys/bob.vk"
      , "--cardano-signing-key", "/devnet/credentials/carol.sk"
      , "--cardano-verification-key", "/devnet/credentials/alice.vk"
      , "--cardano-verification-key", "/devnet/credentials/bob.vk"
      , "--ledger-protocol-parameters", "/devnet/protocol-parameters.json"
      , "--testnet-magic", "42"
      , "--node-socket", "/devnet/node.socket"
      , "--persistence-dir", "/devnet/persistence/carol"
      , "--contestation-period", "3s"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.30
    restart: always

  hydra-tui-1:
    image: ghcr.io/cardano-scaling/hydra-tui:0.22.0
    build:
       context: ../
       target: hydra-tui
    command:
      [ "--connect", "172.16.238.10:4001"
      , "--node-socket", "/devnet/node.socket"
      , "--testnet-magic", "42"
      , "--cardano-signing-key", "/devnet/credentials/alice-funds.sk"
      ]
    volumes:
      - ./devnet:/devnet
    networks:
      hydra_net:
        ipv4_address: 172.16.238.11

  hydra-tui-2:
    image: ghcr.io/cardano-scaling/hydra-tui:0.22.0
    build:
       context: ../
       target: hydra-tui
    command:
      [ "--connect", "172.16.238.20:4001"
      , "--node-socket", "/devnet/node.socket"
      , "--testnet-magic", "42"
      , "--cardano-signing-key", "/devnet/credentials/bob-funds.sk"
      ]
    volumes:
      - ./devnet:/devnet
    networks:
      hydra_net:
        ipv4_address: 172.16.238.21

  hydra-tui-3:
    image: ghcr.io/cardano-scaling/hydra-tui:0.22.0
    build:
       context: ../
       target: hydra-tui
    command:
      [ "--connect", "172.16.238.30:4001"
      , "--node-socket", "/devnet/node.socket"
      , "--testnet-magic", "42"
      , "--cardano-signing-key", "/devnet/credentials/carol-funds.sk"
      ]
    volumes:
      - ./devnet:/devnet
    networks:
      hydra_net:
        ipv4_address: 172.16.238.31

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      hydra_net:
        ipv4_address: 172.16.238.5

  postgres:
    # used by cardano-db-sync & blockfrost-ryo
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ${POSTGRES_ARGS:--c maintenance_work_mem=1GB -c max_parallel_maintenance_workers=4}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - hydra_net

  cardano-db-sync:
    # https://github.com/IntersectMBO/cardano-db-sync/blob/master/docker-compose.yml
    image: ghcr.io/intersectmbo/cardano-db-sync:latest
    environment:
      # For a custom network, a config file is likely required, passed via DB_SYNC_CONFIG
      - DB_SYNC_CONFIG=${DB_SYNC_CONFIG:-/dbsync-config/devnet-config.yaml}
      - DISABLE_LEDGER=${DISABLE_LEDGER:-}
      - NETWORK=${NETWORK:-private}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
      - EXTRA_DB_SYNC_ARGS=${EXTRA_DB_SYNC_ARGS:-}
    depends_on:
      cardano-node:
        condition: service_healthy
      postgres:
        condition: service_healthy
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - ./devnet:/node-ipc # Mount the devnet directory (containing the socket) to /ipc
      - ./patch/migration-4-0003-20210116.sql:/nix/store/2sjgxx8ghn4hhxvl1gj49yaidbin1mg4-schema/migration-4-0003-20210116.sql
      - ./dbsync-config:/dbsync-config
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - hydra_net

  blockfrost-ryo:
    # https://github.com/blockfrost/blockfrost-backend-ryo/tree/master?tab=readme-ov-file#docker
    image: blockfrost/backend-ryo:latest
    environment:
      - NODE_ENV=custom
      - BLOCKFROST_CONFIG_SERVER_LISTEN_ADDRESS=0.0.0.0
      # - PGPASSWORD=
    ports:
      - "3000:3000"
    volumes:
      - ./blockfrost-config:/app/config
    networks:
      - hydra_net

  ogmios:
    # https://github.com/CardanoSolutions/ogmios/blob/master/docker-compose.yml
    image: cardanosolutions/ogmios:latest
    restart: on-failure
    command: [ "--host", "0.0.0.0", "--node-socket", "/ipc/node.socket", "--node-config", "/config/cardano-node.json" ]
    volumes:
      - ./devnet:/config
      - ./devnet:/ipc
      # - ./devnet/db:/db
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    depends_on:
      cardano-node:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ogmios", "health-check"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - hydra_net

  # mesh-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mesh
  #   ports:
  #     - "3003:3000"
  #   depends_on:
  #     - hydra-node-1
  #   networks:
  #     - hydra_net

  kupo:
    image: cardanosolutions/kupo:latest
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    depends_on:
      cardano-node:
        condition: service_healthy
    ports:
      - ${KUPO_PORT:-1442}:1442
    command:
      [
        "--node-socket", "/devnet/node.socket",
        "--node-config", "/devnet/cardano-node.json",
        "--since", "${KUPO_SINCE:-origin}",
        "--match", "${KUPO_MATCH:-*}",
        "--workdir", "/db",
        "--host", "0.0.0.0",
        "--port", "1442"
      ]
    volumes:
      - ./devnet:/devnet
      - db-kupo:/db
    restart: on-failure
    networks:
      - hydra_net

  cardano-wallet:
    image: cardanofoundation/cardano-wallet:latest
    volumes:
      - db-wallet:/wallet-db
      - ./devnet:/ipc
      - ./devnet:/configs/private
    ports:
      - 8090:8090
    entrypoint: []
    command: cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0 --testnet /configs/private/genesis-byron.json
    # user: ${USER_ID}
    restart: on-failure
    depends_on:
      cardano-node:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    networks:
      - hydra_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hydra_net
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hydra_net
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/kafka-topics --bootstrap-server localhost:29092 --list"]
      interval: 15s
      timeout: 5s
      retries: 10

  tx-watcher-mysql:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${TX_WATCHER_MYSQL_DATABASE:-cnio_blockchain_watcher}
      MYSQL_USER: ${TX_WATCHER_MYSQL_USER:-user}
      MYSQL_PASSWORD: ${TX_WATCHER_MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${TX_WATCHER_MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "${TX_WATCHER_MYSQL_PORT:-13306}:3306"
    volumes:
      - mysql-tx-watcher:/var/lib/mysql
    networks:
      - hydra_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${TX_WATCHER_MYSQL_USER:-user}", "--password=${TX_WATCHER_MYSQL_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 10

  tx-watcher-migration:
    image: ${TX_WATCHER_IMAGE:-}
    command: [ "/rpc/bin/rpc-runtime", "migrate", "up" ]
    restart: on-failure
    depends_on:
      tx-watcher-mysql:
        condition: service_healthy
    environment:
      - MYSQL__HOST=tx-watcher-mysql
      - MYSQL__PORT=3306
      - MYSQL__DATABASE=${TX_WATCHER_MYSQL_DATABASE:-cnio_blockchain_watcher}
      - MYSQL__USERNAME=${TX_WATCHER_MYSQL_USER:-user}
      - MYSQL__PASSWORD=${TX_WATCHER_MYSQL_PASSWORD:-password}
    networks:
      - hydra_net

  tx-watcher-seeding:
    image: mysql:8
    command: >
      /bin/sh -c "
        if [ ! -f /var/lib/mysql/seeded.flag ]; then
          echo 'Seeding database...'
          mysql --host=tx-watcher-mysql --user=${TX_WATCHER_MYSQL_USER:-user} --database=${TX_WATCHER_MYSQL_DATABASE:-cnio_blockchain_watcher} -e 'source /config/tx-watcher-config.sql' && \
          touch /var/lib/mysql/seeded.flag
        else
          echo 'Database already seeded. Skipping.'
        fi
      "
    restart: "no"
    depends_on:
      tx-watcher-migration:
        condition: service_completed_successfully
    volumes:
      - ./tx-watcher-config.sql:/config/tx-watcher-config.sql:ro
      - mysql-tx-watcher:/var/lib/mysql
    environment:
      - MYSQL_PWD=${TX_WATCHER_MYSQL_PASSWORD:-password}
    networks:
      - hydra_net

  tx-watcher:
    image: ${TX_WATCHER_IMAGE:-}
    restart: on-failure
    depends_on:
      ogmios:
        condition: service_healthy
      tx-watcher-seeding:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    environment:
      - OGMIOS_URL=ws://ogmios:1337
      - MYSQL__HOST=tx-watcher-mysql
      - MYSQL__PORT=3306
      - MYSQL__DATABASE=${TX_WATCHER_MYSQL_DATABASE:-cnio_blockchain_watcher}
      - MYSQL__USERNAME=${TX_WATCHER_MYSQL_USER:-user}
      - MYSQL__PASSWORD=${TX_WATCHER_MYSQL_PASSWORD:-password}
      - KAFKA_BROKERS=kafka:29092
      - CACHE__EVENT_CONFIGS__TTL=300s
      - CACHE__EVENT_CONFIGS__LIFE_TTL=240s
      - CACHE__EVENT_CONFIGS__SHARDS=1024
      - CACHE__POLICY_ID_CONFIGS__TTL=300s
      - CACHE__POLICY_ID_CONFIGS__LIFE_TTL=240s
      - CACHE__POLICY_ID_CONFIGS__SHARDS=1024
      - CARDANO_NETWORK_ID=42
      - CARDANO_CHAIN_NAME=Devnet
      # - BLOCK_START_SLOT=0
      # - BLOCK_START_EPOCH_TIME=
      # - NETWORK_SLOT_ZERO_TIME='1666656000000'
      # - NETWORK_SLOT_ZERO='0'
      # - NETWORK_SLOT_LENGTH='1000'
      - NETWORK_MAGIC=42
      - FILTER_TYPE=DEFAULT
      - SHOULD_USE_OGMIOS_V6=true
      - IS_WATCHER_ENABLED=true
      - OPTIM_BFF_API_KEY=bf6ad7b7a0131b91
      - BOND_DEX_PUBLISH_TOPIC=bond-dex-tx-publisher
      - DAO_TXN_PUBLISH_TOPIC=dao-drep-txns-publisher
      - DREP_CERTIFICATE_FILTERS=delegateRepresentativeRetirement,stakeDelegation,delegateRepresentativeRegistration,delegateRepresentativeUpdate
      - ENV=development
      - IS_SQL_LOG=false
      - SPENT_OUT_REF_RETENTION_PERIOD=15
      - TRANSACTION_EVENT_SCHEMA_NAME=nio_v1_watcher_transaction_events
    networks:
      - hydra_net

networks:
  hydra_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

volumes:
  db-sync-data:
  postgres:
  db-kupo:
  db-wallet:
  mysql-tx-watcher:
  kafka-data:

secrets:
  postgres_db:
    file: ./dbsync-config/secrets/postgres_db
  postgres_password:
    file: ./dbsync-config/secrets/postgres_password
  postgres_user:
    file: ./dbsync-config/secrets/postgres_user
